mkdirp~/wlogs/$(date+"%Y")/$(date+"%h")
echo"##########$(date)##########
<TO_DO>
	<UDEMY>
		<ul>
			<li></li>
		</ul>
	</UDEMY>
	<IMD_DDP>
		<ul>
			<li></li>
		</ul>
	</IMD_DDP>
	<BORGUTILS>
		<ul>
			<li></li>
		</ul>
	</BORGUTILS>
	<RANDOM>
		<ul>
			<li></li>
		</ul>
	</RANDOM>
</TO_DO>
<THINGS_DONE>
	<UDEMY>
		<ul>
			<li></li>
		</ul>
	</UDEMY>
	<IMD_DDP>
		<ul>
			<li></li>
		</ul>
	</IMD_DDP>
	<RANDOM>
		<ul>
			<li></li>
		</ul>
	</RANDOM>
</THINGS_DONE>
<KNOWLEDGE>
	<RANDOM>
		<ul>
			<li></li>
		</ul>
	</RANDOM>
</KNOWLEDGE>">>~/wlogs/$(date+"%Y")/$(date+"%h")/$(date+"%y")$(date+"%m")$(date+"%d")_$(date+"%a").txt
nano ~/wlogs/$(date+"%Y")/$(date+"%h")/$(date+"%y")$(date+"%m")$(date+"%d")_$(date+"%a").txt
